# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[merge]
require_automerge_label = false
delete_branch_on_merge = true

[approve]
auto_approve_usernames = ["okeeffed"]
