name: Demo CLI Node.js Package
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@okeeffed"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: "yarn workspace @okeeffed/demo-turborepo-cli-github-pkg install --immutable"
        env:
          # Specify custom .npmrc because actions/setup-node@v1 doesn't
          # correctly set registry-url and token at Windows platform
          NPM_CONFIG_USERCONFIG: .npmrc.ci
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "yarn workspace @okeeffed/demo-turborepo-cli-github-pkg run build"
      - run: "npm publish --patch -w=libs/demo-turborepo-cli-github-pkg"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
